files:
  - source: /enhavo/tradukenda/en/ekzercoj/*/*.yml
    ignore:
      - /enhavo/tradukenda/en/enkonduko.md
      - /enhavo/tradukenda/en/post.md
    translation: /enhavo/tradukenda/%two_letters_code%
