files:
  - source: enhavo/tradukenda/en/**/*
    ignore:
      - /enhavo/tradukenda/en/enkonduko.md
      - /enhavo/tradukenda/en/post.md
    translation: enhavo/tradukenda/%two_letters_code%/****/**/
